apiVersion: v1
kind: Namespace
metadata:
  name: dynadoc-system
  labels:
    name: dynadoc-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-service
  labels:
    name: user-service
    app: user-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: template-service
  labels:
    name: template-service
    app: template-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: file-service
  labels:
    name: file-service
    app: file-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared-infrastructure
  labels:
    name: shared-infrastructure
    app: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
